# docker stack deploy -c stack.yml jupyter
version: "3.7"
networks:
  mysparkify:
services:
  spark:
    image: jupyter/all-spark-notebook:latest
    ports:
    - "8888:8888/tcp"
    - "4040:4040/tcp"
    networks:
    - mysparkify
    working_dir: /home/$USER/work
    environment:
      CHOWN_HOME: "yes"
      GRANT_SUDO: "yes"
      NB_UID: 1000
      NB_GID: 100
      NB_USER: $USER
      NB_GROUP: staff
    user: root
    deploy:
     replicas: 1
     restart_policy:
       condition: on-failure
    volumes:
    - $PWD/workflow:/home/$USER/work
  adminer:
    image: adminer:latest
    ports:
    - "8080:8080/tcp"
    networks:
    - mysparkify
    deploy:
     restart_policy:
       condition: on-failure